apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/prometheus
  - ../base/scylladb
#  - mediastorage-service.yaml
configMapGenerator:
  - name: uoc-animals-services-cm
    behavior: create
    literals:
      - scylladb-ip=192.168.2.126
secretGenerator:
  - name: uoc-animals-database-creds
    literals:
    - username=animalsapp
    - password=1f2d1e2e67df
      