apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/prometheus
  - ../base/scylladb
  - mediastorage-pv.yaml
  - mediastorage-service.yaml
  - agents-service.yaml
  - routing.yaml
  - watermark-evt.yaml
  - activities-broker.yaml
  - activities-trigger.yaml
  - telegram-sink.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: uoc-animals-services-cm
    namespace: default
    behavior: create
    literals:
      - scylladb-ip=10.43.208.229
      - msver=0.1.1
      - agver=0.1.0
secretGenerator:
  - name: uoc-animals-database-creds
    namespace: default
    literals:
    - username=animalsapp
    - password=1f2d1e2e67df
      