apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/prometheus
  - ../base/scylladb
  - mediastorage-pv.yaml
  - mediastorage-service.yaml
  - agents-service.yaml
  - routing.yaml
#  - temp-storage.yaml
#  - watermark-evt.yaml
  - activities-broker.yaml
#  - activities-trigger.yaml
#  - telegram-sink.yaml
  - animals-cm.yaml
  - mqtt-broker.yaml
  - mqtt-pipe.yaml
  - sensors-evt.yaml
  - telegram-source-new.yaml
  - telegram-source-pipe.yaml
  - telegram-evt.yaml
  - telegram-broker.yaml
  - telegram-pipe.yaml
  - telegram-new-sink.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: uoc-animals-services-cm
    namespace: default
    behavior: merge
    literals:
      - scylladb-ip=10.43.239.157
      - msver=0.1.11
      - agver=0.1.0
      - imagebrokerurl=http://broker-ingress.knative-eventing.svc.cluster.local/default/image-broker
      - telegrambrokerurl=http://broker-ingress.knative-eventing.svc.cluster.local/default/telegram-broker
      - mediastorageurl=http://mediastorage.default.svc.cluster.local
      - videodevice=video10
secretGenerator:
  - name: uoc-animals-database-creds
    namespace: default
    literals:
    - username=animalsapp
    - password=1f2d1e2e67df
      