apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediastorage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
---