apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: mqtt-source
  namespace: default
  annotations:
    trait.camel.apache.org/mount.configs: "secret:mqtt-credentials"
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: mqtt-source
    properties:
      brokerUrl: "tcp://mosquitto-mqtt:1883"
      topic: "mytopic"
      clientId: "animal-test"
      username: ${mqtt.username}
      password: ${mqtt.password}
  sink:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: mqtt-camel-broker