# A default broker
# apiVersion: eventing.knative.dev/v1
# kind: Broker
# metadata:
#   name: sensor-broker
#   namespace: default
#   annotations:
#     # Note: you can set the eventing.knative.dev/broker.class annotation to change the class of the broker.
#     # The default broker class is MTChannelBasedBroker, but Knative also supports use of the other class.
#     eventing.knative.dev/broker.class: MTChannelBasedBroker
# spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensorcontrol
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: sensorcontrol
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector:
        kubernetes.io/hostname: uoc-bpim4zero-01
      tolerations:
      - key: memorytype
        operator: Equal
        value: low
        effect: NoSchedule
      containers:
        - name: sensorcontrol
          image: ghcr.io/jgnoguer/sensorcontrol:0.1.1
          env:
          - name: VIDEO_DEVICE
            valueFrom:
              configMapKeyRef:
                name: uoc-animals-services-cm
                key: videodevice
          - name: TELEGRAM_BROKER
            valueFrom:
              configMapKeyRef:
                name: uoc-animals-services-cm
                key: telegrambrokerurl
      #     volumeMounts:
      #       - name: video-volume
      #         mountPath: /videoonhost
      # volumes: 
      #   - name: video-volume
      #     hostPath: 
      #       path: /dev/video10
      #       type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: sensorcontrol-svc
  namespace: default
spec:
  selector:
    app: sensorcontrol
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
# Knative Eventing Trigger to trigger the sensorcontrol service
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sensorcontrol
  namespace: default
spec:
  broker: mqtt-camel-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: sensorcontrol-svc

