apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: telegram-sink-pipe
  namespace: camel-k
  annotations:
    trait.camel.apache.org/mount.configs: "secret:telegram-credentials"
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: activities-broker
    properties:
      type: moderated-comment
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: telegram-sink
    properties:
      authorizationToken: "${telegram.authorizationToken}"