apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: telegram-sink-pipe
  namespace: camel-k
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: activities-broker
    properties:
      type: moderated-comment
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: telegram-sink
    properties:
      authorizationToken: "8002248014:AAHouz7oU_miCzhFDoSb2Mr46t4zVP14WiY"