apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: telegram-pipe
  annotations:
    trait.camel.apache.org/mount.configs: "secret:telegram-credentials"
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: telegram-broker
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: telegram-new-sink
      namespace: default
    properties:
      authorizationToken: ${telegram.authorizationToken}
      chatId: ${telegram.chatId}