apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus-community/kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 50m