apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 1m
  values:
    nodeSelector:
      istio-gateway: true    
    tolerations:
    - key: istio-ingress
      operator: Equal
      value: compatible
      effect: NoSchedule
    - key: memorytype
      operator: Equal
      value: low
      effect: NoSchedule