apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - helm-release-istio-base.yaml
  - helm-release-istiod.yaml
  - helm-release-gateway.yaml
  

