---
apiVersion: v1
kind: Secret
metadata:
  name: tekton-knative
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    BLABLABLA
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
secrets:
  - name: tekton-knative