apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  name: mediastorage
  namespace: default
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/updateTimestamp: "2025-05-03T00:37:53Z"
        client.knative.dev/user-image: docker.io/jgnoguer/mediastore:latest
      creationTimestamp: null
    spec:
      nodeSelector:
        longhorn: compatible
      containers:
      - image: docker.io/jgnoguer/mediastore:latest
        name: ""
        resources: {}
        volumeMounts:
            - mountPath: /data
              name: mydata
              readOnly: false
      volumes:
        - name: mydata
          persistentVolumeClaim:
            claimName: noreplicavolume
            readOnly: false
status: {}
