apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - scylladb-operator.yaml
  - 00_namespace.yaml
  - 10_csidriver.yaml
  - 10_driver_serviceaccount.yaml
  - 10_provisioner_clusterrole.yaml
  - 20_provisioner_clusterrolebinding.yaml
  - 50_daemonset.yaml
