---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylladb-config
  namespace: scylla
data:
  scylla.yaml: |
    authenticator: PasswordAuthenticator
    authorizer: CassandraAuthorizer
    # Other options
    # 29/05/2025
---
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: scylladb-uoc
  namespace: scylla
spec:
  repository: docker.io/scylladb/scylla
  version: 2025.1.2
  agentVersion: 3.5.0
  developerMode: true
  automaticOrphanedNodeCleanup: true
  sysctls:
  - fs.aio-max-nr=1048576
  datacenter:
    name: animals
    racks:
    - name: db-rack
      members: 2
      scyllaConfig: scylladb-config
      storage:
        capacity: 12Gi
        storageClassName: scylladb-local-xfs
      resources:
        requests:
          cpu: 1
          memory: 1Gi
        limits:
          cpu: 3
          memory: 2Gi
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - uoc-rock3a-02
                - uoc-rock3a-03
        tolerations:
        - key: scylla-operator.scylladb.com/dedicated
          operator: Equal
          value: scyllaclusters
          effect: NoSchedule
        - key: scylla-operator.scylladb.com/dedicated
          operator: Equal
          value: scyllaclusters
          effect: NoExecute
