deletingConfirmationFlag: true
#defaultSettings:
#  taintToleration: memorytype=low:NoSchedule;
longhornManager:
  tolerations:
  - key: memorytype
    operator: Equal
    value: low
    effect: NoSchedule
  nodeSelector:
    longhorn: compatible
longhornDriver:
  tolerations:
  - key: memorytype
    operator: Equal
    value: low
    effect: NoSchedule
  nodeSelector:
    longhorn: compatible
longhornUI:
  nodeSelector:
    longhorn: compatible