defaultSettings:
  taintToleration:
    - key: memorytype
      operator: Equal
      value: low
      effect: NoSchedule
    - key: memorytype
      operator: Equal
      value: low
      effect: NoExecute
longhornManager:
  tolerations:
  - key: memorytype
    operator: Equal
    value: low
    effect: NoSchedule
  - key: memorytype
    operator: Equal
    value: low
    effect: NoExecute
  nodeSelector:
    longhorn: compatible
longhornDriver:
  tolerations:
  - key: memorytype
    operator: Equal
    value: low
    effect: NoSchedule
  - key: memorytype
    operator: Equal
    value: low
    effect: NoExecute
  nodeSelector:
    longhorn: compatible