apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serving-crds.yaml
#  - operator.yaml
#  - namespace.yaml
#  - knative-serving.yaml
#  - net-istio.yaml
#  - knative-eventing.yaml
#  - serving-default-domain.yaml
