apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |

    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout

    password_file /mosquitto/config/password.txt
    
    # MQTTS listener
    listener 8883
    protocol mqtt

    cafile /mosquitto/certs/ca-chain.pem
    certfile /mosquitto/certs/cert.pem
    keyfile /mosquitto/certs/privkey.pem
