---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: zigbee2mqtt
  chart:
    spec:
      chart: zigbee2mqtt
      version: '2.4.0'
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: flux-system
      interval: 10m
  values:
    statefulset:
      nodeSelector:
        zigbee2mqtt=compatible
      tolerations:
        - key: memorytype
          operator: Equal
          value: low
          effect: NoSchedule
    zigbee2mqtt:
      mqtt:
        # -- Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
        server: "mqtt://10.42.14.105:1883"