apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: zigbee2mqtt
    namespace: flux-system
spec:
    interval: 5m
    targetNamespace: zigbee2mqtt
    chart:
        spec:
            chart: zigbee2mqtt
            version: '1.37.1'
            sourceRef:
                kind: HelmRepository
                name: zigbee2mqtt
                namespace: flux-system
            interval: 10m
    values:
      statefulset:
        nodeSelector:
          zigbee2mqtt=compatible
        tolerations:
         - key: memorytype
           operator: Equal
           value: low
           effect: NoSchedule