---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: camelk-release
  namespace: default
#  namespace: camel-k
spec:
  chart:
    spec:
      chart: camel-k
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: camelk-repo
      version: 2.6.0
  interval: 1m0s
  values:
    operator:
      nodeSelector:
        camelk: compatible      