apiVersion: apps/v1
kind: Deployment
metadata:
  name: clear-nginx-deployment
spec:

  selector:
    matchLabels:
      app: clear-nginx
  template:
    metadata:
      labels:
        app: clear-nginx
    spec:
      nodeSelector:
        longhorn: compatible
      containers:
      - name: clear-nginx
        image: nginx
        volumeMounts:
        - mountPath: /data
          name: site-data
        ports:
        - containerPort: 80
      volumes:
      - name: site-data
        persistentVolumeClaim:
          claimName: noreplicavolume